# Generated by Django 5.2 on 2025-04-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_noticia_imagem_url_noticia_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
