# Generated by Django 5.2.1 on 2025-05-26 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_noticia_destaque'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Imagem'), ('video', 'Vídeo')], max_length=10)),
                ('texto', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='conteudos/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='news.noticia')),
            ],
        ),
    ]
